"""Check forecast + observation coverage of candidate replay events (v2 #18).

    uv run python -m pipelines.check_events --source wb2

An event is USABLE only if, for its window and regions, (a) HRES runs exist for every lead
Day 1-10 of at least one valid day, (b) IMD truth exists, and (c) IMD shows at least one
heavy-rain subdivision-day (area mean >= 64.5 mm) there. Results -> docs/replay_events.md
and artifacts/<SOURCE>/events_coverage.json. Event windows are excluded from training and
calibration by pipelines.dataset regardless of the outcome.
"""

from __future__ import annotations

import argparse
import json

import pandas as pd

from ml.config import REPO_DIR, load_config
from pipelines.common import artifact_dir, table_path

HEAVY = 64.5


def check(source: str) -> list[dict]:
    events = load_config("replay_events")["events"]
    t = pd.read_parquet(
        table_path(source),
        columns=["init_date", "valid_date", "lead_day", "region_id", "fc", "obs", "bust", "split"],
    )
    t["valid_date"] = pd.to_datetime(t["valid_date"])
    leads_all = sorted(t["lead_day"].unique())
    names = {}
    try:
        from ml.regions import load_regions

        names = load_regions()["name"].to_dict()
    except Exception:  # noqa: BLE001
        pass
    out = []
    for e in events:
        lo, hi = (pd.Timestamp(str(x)) for x in e["window"])
        w = t[(t["valid_date"] >= lo) & (t["valid_date"] <= hi) & t["region_id"].isin(e["regions"])]
        rec = {
            "id": e["id"],
            "title": e["title"],
            "window": [str(lo.date()), str(hi.date())],
            "regions": e["regions"],
        }
        if w.empty:
            rec.update(
                usable=False,
                reason="no forecasts in the downloaded data (WeatherBench 2 HRES covers 2016-2022; BustGuard fetches JJAS 2018-2022 only)",
            )
            out.append(rec)
            continue
        cov = w.groupby("valid_date")["lead_day"].nunique()
        full_days = cov[cov == len(leads_all)].index
        obs = w.dropna(subset=["obs"])
        d1 = obs[obs["lead_day"] == 1]
        heavy = d1[d1["obs"] >= HEAVY]
        peak = d1.loc[d1["obs"].idxmax()] if len(d1) else None
        rec.update(
            forecast_valid_days=int(w["valid_date"].nunique()),
            full_lead_coverage_days=int(len(full_days)),
            imd_days=int(d1["valid_date"].nunique()),
            heavy_subdivision_days=int(len(heavy)),
            peak={
                "valid_date": str(peak["valid_date"].date()),
                "region_id": peak["region_id"],
                "region": names.get(peak["region_id"], peak["region_id"]),
                "imd_mm": round(float(peak["obs"]), 1),
                "hres_day1_mm": round(float(peak["fc"]), 1),
            }
            if peak is not None
            else None,
            busts_any_lead=int(obs["bust"].sum()),
            split=str(w["split"].mode().iat[0]),
        )
        ok = len(full_days) > 0 and len(d1) > 0 and len(heavy) > 0
        rec["usable"] = bool(ok)
        if not ok:
            rec["reason"] = (
                "no full Day 1-10 coverage"
                if not len(full_days)
                else (
                    "no IMD heavy-rain subdivision-day in the window"
                    if not len(heavy)
                    else "no IMD data"
                )
            )
        out.append(rec)
    return out


def write_doc(results: list[dict]) -> None:
    L = [
        "# Replay events: data coverage check",
        "",
        "Generated by `python -m pipelines.check_events`. Candidates come from `backend/configs/replay_events.yaml`.",
        "Every window is excluded from model training and calibration. An event is used for replay only if",
        "HRES forecasts cover all lead days (Day 1-10) for at least one valid day, IMD gridded rainfall exists, and IMD",
        "shows at least one heavy-rain subdivision-day (area mean >= 64.5 mm) in the window. Numbers are subdivision area means.",
        "",
        "| Event | Window | Usable | Split | Peak IMD area-mean (subdivision, day) | HRES Day-1 there | Heavy subdivision-days | Busts (any lead) | Note |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        pk = r.get("peak")
        peak = f"{pk['imd_mm']} mm ({pk['region']}, {pk['valid_date']})" if pk else "n/a"
        L.append(
            f"| {r['title']} | {r['window'][0]} to {r['window'][1]} | {'yes' if r['usable'] else 'no'} | {r.get('split', 'n/a')} | {peak} | "
            f"{pk['hres_day1_mm'] if pk else 'n/a'} mm | {r.get('heavy_subdivision_days', 'n/a')} | {r.get('busts_any_lead', 'n/a')} | {r.get('reason', '')} |"
        )
    L += [
        "",
        "Split = where the event's dates fall: train/calibration events are still out-of-sample because their windows were removed from fitting.",
    ]
    (REPO_DIR / "docs" / "replay_events.md").write_text("\n".join(L) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", default="wb2", choices=["synthetic", "wb2", "open_meteo"])
    args = ap.parse_args(argv)
    res = check(args.source)
    (artifact_dir(args.source) / "events_coverage.json").write_text(json.dumps(res, indent=1))
    if args.source == "wb2":
        write_doc(res)
    for r in res:
        print(
            f"[events] {r['id']:24s} usable={r['usable']!s:5s} {r.get('reason', '')} peak={r.get('peak')}"
        )


if __name__ == "__main__":
    main()
