"""Shared helpers for the pipeline CLIs: source names and artifact paths.

Sources:
  synthetic  -> files prefixed ``SYNTHETIC_`` / artifacts in ``artifacts/SYNTHETIC``
  wb2        -> WeatherBench 2 (HRES + GraphCast + ERA5), real data
  open_meteo -> Open-Meteo previous runs (Day 1-7), real data
"""

from __future__ import annotations

from pathlib import Path

from ml.config import ARTIFACTS_DIR, PROCESSED_DIR

SOURCES = {"synthetic": "SYNTHETIC", "wb2": "wb2", "open_meteo": "open_meteo"}


def tag(source: str) -> str:
    if source not in SOURCES:
        raise SystemExit(f"unknown source {source!r}; choose from {list(SOURCES)}")
    return SOURCES[source]


def raw_path(source: str) -> Path:
    return PROCESSED_DIR / f"{tag(source)}_raw.parquet"


def table_path(source: str) -> Path:
    return PROCESSED_DIR / f"{tag(source)}_table.parquet"


def artifact_dir(source: str) -> Path:
    d = ARTIFACTS_DIR / tag(source)
    d.mkdir(parents=True, exist_ok=True)
    return d


def banner(source: str) -> str:
    if source == "synthetic":
        return (
            "!!! SYNTHETIC DATA: generated by ml/data/synthetic.py. Not observations, not "
            "forecasts. Results only demonstrate that the pipeline works. !!!"
        )
    return ""
